#!/usr/bin/env bash
# Generator for the AutomationTools breakaway tag pool (100 tags).
# Produces: country_tags file, localisation snippet, and the pool scripted-effects file.
set -euo pipefail

MOD="C:/Development/EU4Modding/AutomationTools"
OUT_TAGS="$MOD/common/country_tags/atools_tags.txt"
OUT_FX="$MOD/common/scripted_effects/atools_pool_effects.txt"
OUT_LOC="C:/Users/isaac/AppData/Local/Temp/claude/C--Development-EU4Modding/3c9e688a-fdd9-4021-bb8e-7492116cd625/scratchpad/atools_pool_loc.txt"
AREAFILE="C:/Program Files (x86)/Steam/steamapps/common/Europa Universalis IV/map/area.txt"

PREFIXES=(AT AU AV AW AX AY AZ BT BU BV)
ADJ=(Free United Old New High Grand Little Upper Lower Middle)
NOUN=(Freehold State Commonwealth Confederation Union League Dominion March Territory Republic)

# Build the ordered tag list.
TAGS=()
for p in "${PREFIXES[@]}"; do for d in 0 1 2 3 4 5 6 7 8 9; do TAGS+=("${p}${d}"); done; done

# --- 1) country_tags ---
{
  echo "# AutomationTools - reserved tag pool for region-based breakaway (spawned at runtime)."
  echo "# GENERATED by scratchpad/gen_pool.sh - do not hand-edit; all point at one shared file."
  for t in "${TAGS[@]}"; do echo "$t = \"countries/atools_pool.txt\""; done
} > "$OUT_TAGS"

# --- 2) localisation snippet (name + adjective per tag) ---
{
  i=0
  for pi in "${!PREFIXES[@]}"; do
    for d in 0 1 2 3 4 5 6 7 8 9; do
      t="${PREFIXES[$pi]}${d}"
      name="${ADJ[$pi]} ${NOUN[$d]}"
      echo " ${t}:0 \"${name}\""
      echo " ${t}_ADJ:0 \"${name}\""
      i=$((i+1))
    done
  done
} > "$OUT_LOC"

# --- 3) pool scripted effects ---
{
  cat <<'HEADER'
##############################################################################
# AutomationTools - BACKEND (region-breakaway tag pool). GENERATED by
# scratchpad/gen_pool.sh - do not hand-edit; re-run the generator to change it.
#
# atools_pool_select : scan for ONE nation that still holds an EXCLAVE province
#   (is_overseas = yes, i.e. no land route to its capital), save it + a seed
#   province (which fixes the target REGION), set atools_breakaway_pending.
#   First match wins (flag stops the scan).
#
# atools_pool_spawn_effect : recycle dead pool tags, then for each free tag run
#   a select and, if a target was found, core that nation's EXCLAVE provinces in
#   the seed's region and release the tag as a new independent nation. Grouped by
#   region so separate exclave blocks become SEPARATE nations. Stops early once a
#   select finds nothing (atools_pool_exhausted). Contiguous land is never touched.
##############################################################################

atools_pool_select = {
	clr_global_flag = atools_breakaway_pending
	every_country = {
		limit = { NOT = { has_global_flag = atools_breakaway_pending } num_of_cities = 1 }
		save_event_target_as = atools_split_nation
		if = {
			limit = { any_owned_province = { is_city = yes is_overseas = yes } }
			random_owned_province = {
				limit = { is_city = yes is_overseas = yes }
				save_event_target_as = atools_split_seedprov
			}
			set_global_flag = atools_breakaway_pending
		}
	}
}

atools_pool_spawn_effect = {
	clr_global_flag = atools_pool_exhausted

	# --- Recycle: free any pool tag whose nation has died (annexed/collapsed). ---
HEADER

  for t in "${TAGS[@]}"; do
    echo "	if = { limit = { has_global_flag = atools_pool_${t}_used NOT = { exists = ${t} } } clr_global_flag = atools_pool_${t}_used }"
  done

  echo ""
  echo "	# --- Spawn: one free tag per unclaimed out-of-region region-block. ---"
  for t in "${TAGS[@]}"; do
    cat <<BLOCK
	if = {
		limit = { NOT = { has_global_flag = atools_pool_${t}_used } NOT = { has_global_flag = atools_pool_exhausted } }
		atools_pool_select = yes
		if = {
			limit = { has_global_flag = atools_breakaway_pending }
			event_target:atools_split_nation = {
				every_owned_province = { limit = { is_city = yes is_overseas = yes region = event_target:atools_split_seedprov } add_core = ${t} }
				release = ${t}
			}
			${t} = {
				change_government = monarchy
				add_government_reform = autocracy_reform
				set_capital = event_target:atools_split_seedprov
				atools_name_by_area = yes
			}
			set_global_flag = atools_pool_${t}_used
		}
		else = { set_global_flag = atools_pool_exhausted }
	}
BLOCK
  done

  echo "}"

  # --- atools_name_by_area: name the current country after its capital's AREA ---
  # override_country_name prints the loc key's text verbatim; area names ARE loc keys
  # (ordos_area -> "Ordos"), so this yields location names. One branch per vanilla area.
  echo ""
  echo "# Name the current country after its capital province's area (override prints the"
  echo "# area loc key's text). GENERATED from map/area.txt."
  echo "atools_name_by_area = {"
  first=1
  while read -r a; do
    [ -z "$a" ] && continue
    if [ "$first" = 1 ]; then
      echo "	if = { limit = { capital_scope = { area = ${a} } } override_country_name = ${a} }"
      first=0
    else
      echo "	else_if = { limit = { capital_scope = { area = ${a} } } override_country_name = ${a} }"
    fi
  done < <(grep -oE "^[a-z][a-z_0-9]* *= *\{" "$AREAFILE" | sed -E 's/ *= *\{//' | sort -u)
  echo "}"
} > "$OUT_FX"

echo "Wrote:"
echo "  $OUT_TAGS   ($(grep -c '=' "$OUT_TAGS") lines)"
echo "  $OUT_FX     ($(wc -l < "$OUT_FX") lines)"
echo "  $OUT_LOC    ($(wc -l < "$OUT_LOC") loc lines)"
